### ISSUE TITLE
Create API

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#33]
## Required functionalities

- [x] Create email+code login
- [x] Create GitHub login (#3)
- [ ] Create Google login(#4)
- [x] Add email module
- [ ] Create functionality to generate access tokens from refresh token
- [x] Create authentication for accessing API using JWT
- [ ] Create authentication for accessing API using token. Restrictions on:
       - Deleting self
       - Modifying self
       - Other User specific 
- [x] Create CRUD of users
- [x] Create CRUD of projects
- [x] Create CRUD of secrets (#69)
- [x] Create CRUD of environment (#66)
- [x] Create CRUD of API keys
- [ ] Create tests for all of the above

**Comment by Abbhiishek** [comment]
hey @rajdip-b  @kriptonian1  are we planning to use any library for github and google auth ?

**Comment by rajdip-b** [comment]
Nothing in specific. We're open to options!

**Comment by Abbhiishek** [comment]
I can suggest clerk for the following reasons

- they have a webhook that get triggered on user logged in and user updating and soo on
- It support out of box for multiple auth provider without using single API key for each provider (off course we have an option to that to improve brand.)
- It also gives user data about its logged in devices session and organisation level authentication is possible too.

Reference : https://clerk.com/

**Comment by rajdip-b** [comment]
@Abbhiishek Even I was thinking about Clerk. Just keep in mind, we need the name, email and profile picture once the use signs up!

**Comment by Abbhiishek** [comment]
sure @rajdip-b

**Comment by rajdip-b** [comment]
Okei then lmk as and when you progress, you are already assigned those issues!
