### ISSUE TITLE
WEB: suggesting changes while adding waitlist

### ISSUE THREAD

**Issue by HarshPatel5940** [keyshade-xyz/keyshade#463]
# Description 
- [x] [chore] Right now after adding the user to the waitlist there the text field remains the same, instead lets clear the text field. (#481)
- [x] [chore] Perform some validation on the email field as `ff@ff` and other things is allowed which should not be allowed. (#487)
- [x] [chore] Only show toast when the whitelist response is successful. (#490)
- [ ] [feat] Check if user has already whitelisted. (#492)

---
Target file: https://github.com/keyshade-xyz/keyshade/blob/72281e66569b05011a7b79a94ae502eaac0b3a6d/apps/web/src/components/hero/index.tsx

**Comment by rajdip-b** [comment]
@kriptonian1 can you review this once? If valid, please open up 4 separate issues.

**Comment by Nil2000** [comment]
For the 4th case, If anyone try to hit the end point using the same email, the response says Successfully subscribed. It should either say already subscribed or give error at the response. 
May be we require DB to tackle this. 🤔

**Comment by HarshPatel5940** [comment]
> For the 4th case, If anyone try to hit the end point using the same email, the response says `Successfully subscribed`. It should either say `Already subscribed` or give error at the response. May be we require `DB` to tackle this. Or may be add some settings in `mailchimp`🤔


As far as i remember to tackle that, we need to hash the email and check if the mail exist in the mailing list. That would be another request from our side as much as i remember. Need to explore myself.

Alternatively we have https://listmonk.app/ just wanted to throw this in cause its a cool mailing list manager which is easy to use.

**Comment by kriptonian1** [comment]
> For the 4th case, If anyone try to hit the end point using the same email, the response says `Successfully subscribed`. It should either say `Already subscribed` or give error at the response. May be we require `DB` to tackle this. Or may be add some settings in `mailchimp`🤔

I am not sure if we can get any such response from Mailchimp or not

**Comment by kriptonian1** [comment]
> > For the 4th case, If anyone try to hit the end point using the same email, the response says `Successfully subscribed`. It should either say `Already subscribed` or give error at the response. May be we require `DB` to tackle this. Or may be add some settings in `mailchimp`🤔
> 
> As far as i remember to tackle that, we need to hash the email and check if the mail exist in the mailing list. That would be another request from our side as much as i remember. Need to explore myself.
> 
> Alternatively we have https://listmonk.app/ just wanted to throw this in cause its a cool mailing list manager which is easy to use.

Actually we are using Mailchimp because this is what our marketing team is using, not sure if we can do campaigns through listmonk

**Comment by HarshPatel5940** [comment]
> Actually we are using Mailchimp because this is what our marketing team is using, not sure if we can do campaigns through listmonk

Hmm, got it. 👍🏼

**Comment by kriptonian1** [comment]
<img width="666" alt="image" src="https://github.com/user-attachments/assets/1a976928-9a0d-4779-8f98-1ca675ea0b70">
@HarshPatel5940 I think in 2nd point this what you mentioned, right?

**Comment by HarshPatel5940** [comment]
> <img alt="image" width="666" src="https://private-user-images.githubusercontent.com/74916308/372004375-1a976928-9a0d-4779-8f98-1ca675ea0b70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2OTIyODgsIm5iZiI6MTcyNzY5MTk4OCwicGF0aCI6Ii83NDkxNjMwOC8zNzIwMDQzNzUtMWE5NzY5MjgtOWEwZC00Nzc5LThmOTgtMWNhNjc1ZWEwYjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDEwMjYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNzE3YWRlYmQxZDY4NGIzYTJjMjk4ZmZkOTRmMjM5ODNmNDYwMWUwZDg2MTUwZjUzODBhZjVkMDE0NGQ5YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S52HyVDWfyKyeWZ6YcvDD9H3g3k5lW0414EZ35R82YE">
> @HarshPatel5940 I think in 2nd point this what you mentioned, right?

No i meant it allows ff@ff ... it should not allow that right.. instead ff@ff.com can be allowed ig.

**Comment by bansal-harsh-2504** [comment]
can I contribute to this issue please?

**Comment by kriptonian1** [comment]
@bansal-harsh-2504 sure

**Comment by bansal-harsh-2504** [comment]
@kriptonian1 Do I need to rebuild using Docker after each file change? It takes around 300 seconds for each build. This is my first time using Docker, so please bear with me.

**Comment by rajdip-b** [comment]
I don't think you need docker in the first place. Docker is for self-hosting it (partly). You should be using the `pnpm` commands for this ideally.

Do go through our docs to understand how to get this done: 
- [Get your envs set up](https://docs.keyshade.xyz/contributing-to-keyshade/environment-variables)
- [Get your environment up and running](https://docs.keyshade.xyz/contributing-to-keyshade/setting-things-up#setting-up-the-development-environment)
- [Run the API](https://docs.keyshade.xyz/contributing-to-keyshade/running-things-locally/running-the-api)
- [Run the platform or the web](https://docs.keyshade.xyz/contributing-to-keyshade/running-things-locally/running-the-web-app)

**Comment by bansal-harsh-2504** [comment]
@rajdip-b  @kriptonian1 I am done with (2.[chore] Perform some validation on the email field as ff@ff and other things is allowed which should not be allowed.)
So do i need to create pr for this issue or you guys are creating seperate issues.

**Comment by rajdip-b** [comment]
We don't want to impose any restriction on the domain. Just check for this regex: `.[\w]{2,}`

**Comment by bansal-harsh-2504** [comment]
@rajdip-b  Could you please share the Mailchimp API URL to check if an email has already been waitlisted? Appreciate your help!

**Comment by poswalsameer** [comment]
Hi @rajdip-b, I have got the issue and am done with almost half of the code changes. Please assign this to me, so that I can start working on this issue. Thanks!

**Comment by rajdip-b** [comment]
Hey @poswalsameer, Harsh has already dropped 2 PRs for the first 2 points. I can assign this to you along with him, but I would recommend you to not work on the features that Harsh has already worked on.

**Comment by poswalsameer** [comment]
> Hey @poswalsameer, Harsh has already dropped 2 PRs for the first 2 points. I can assign this to you along with him, but I would recommend you to not work on the features that Harsh has already worked on.

Hi, thanks for assigning the issue. Yes, I have seen the PRs dropped for the first 2 points, will be working on the other two.

**Comment by bansal-harsh-2504** [comment]
@rajdip-b The third point is unnecessary and can be disregarded.

**Comment by poswalsameer** [comment]
> @rajdip-b The third point is unnecessary and can be disregarded.

Hi, thanks for letting me know about this. Will take care of this thing.

**Comment by rajdip-b** [comment]
Special thanks to @HarshPatel5940 for bug hunting <3

**Comment by poswalsameer** [comment]
Hi @rajdip-b, raised PR #483 to solve the issue mentioned in point 4. The issue mentioned in point 3 is not significant and has already been taken care of by the current codebase. Please review this PR so it can get merged. Thank You!

**Comment by HarshPatel5940** [comment]
> Special thanks to @HarshPatel5940 for bug hunting <3

Happy to help!

**Comment by HarshPatel5940** [comment]
> Hi @rajdip-b, raised PR #483 to solve the issue mentioned in point 4. The issue mentioned in point 3 is not significant and has already been taken care of by the current codebase. Please review this PR so it can get merged. Thank You!

Hi Sameer,
  Point 3 is actually valid here cause I remember turning off the wifi and still getting a successfully added to the waitlist even when the request failed due to no network.

If you can verify that this situation, it would be helpful.

**Comment by poswalsameer** [comment]
> > Hi @rajdip-b, raised PR #483 to solve the issue mentioned in point 4. The issue mentioned in point 3 is not significant and has already been taken care of by the current codebase. Please review this PR so it can get merged. Thank You!
> 
> Hi Sameer, Point 3 is actually valid here cause I remember turning off the wifi and still getting a successfully added to the waitlist even when the request failed due to no network.
> 
> If you can verify that this situation is not happening, it would be helpful.


Thanks for pointing out the exact issue. I will start working on this, till then you can review the code for point 4.

**Comment by HarshPatel5940** [comment]
> Thanks for pointing out the exact issue. I will start working on this, till then you can review the code for point 4.n

mhmm, noted.

**Comment by bansal-harsh-2504** [comment]
> > Hi @rajdip-b, raised PR #483 to solve the issue mentioned in point 4. The issue mentioned in point 3 is not significant and has already been taken care of by the current codebase. Please review this PR so it can get merged. Thank You!
> 
> Hi Sameer,
>   Point 3 is actually valid here cause I remember turning off the wifi and still getting a successfully added to the waitlist even when the request failed due to no network.
> 
> If you can verify that this situation is not happening, it would be helpful.

Thank you for pointing that out. After reviewing the code, I realize you are correct. 

I am done with the solution. @rajdip-b @poswalsameer May I raise a PR for point 3?

**Comment by HarshPatel5940** [comment]
> I am done with the solution. @rajdip-b @poswalsameer May I raise a PR for point 3?

Feel free to do it :D

**Comment by poswalsameer** [comment]
> > > Hi @rajdip-b, raised PR #483 to solve the issue mentioned in point 4. The issue mentioned in point 3 is not significant and has already been taken care of by the current codebase. Please review this PR so it can get merged. Thank You!
> > 
> > 
> > Hi Sameer,
> > Point 3 is actually valid here cause I remember turning off the wifi and still getting a successfully added to the waitlist even when the request failed due to no network.
> > If you can verify that this situation is not happening, it would be helpful.
> 
> Thank you for pointing that out. After reviewing the code, I realize you are correct.
> 
> I am done with the solution. @rajdip-b @poswalsameer May I raise a PR for point 3?

Sure, go for it.

**Comment by rajdip-b** [comment]
Impressive work guys!
