### ISSUE TITLE
Update Swagger Docs

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#82]
## Description

Currently, keyshade API uses Swagger to view and manage the API docs. Unfortunately, only the `auth` module has the proper docs about the API. We would like to add proper documentation to each and every controller in each and every module. 

**NOTE: This is the master issue. All other linked child issues would require to fulfill the coverage requirements mentioned in this issue.**

## Checklist

- [ ] Update docs of `project` module (#83)
- [ ] Update docs of `secret` module (#85)
- [ ] Update docs of `api-keys` module (#86)
- [ ] Update docs of `envorionment` module (#84)

## Things to cover

Each of the requests should have the following docs covered:
- Title
- Description.
- Path variables and query parameters.
- All response types along with status, description, and the response body (you may use the swagger UI or your fav API tool for interacting with the API).
